import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { WebVitals } from "@/components/web-vitals";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { CartProvider } from "@/app/cartContext";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster />
        <CartProvider>
          <Providers>
            <WebVitals />
            <main>{children}</main>
            <Analytics />
            <SpeedInsights />
          </Providers>
        </CartProvider>
      </body>
    </html>
  );
}
